
-- VERIFICAR TÍTULOS SEM NÚMERO
SELECT TITULOS.NUMERO, 
((SELECT DISTINCT NUMERO FROM NS.DF_DOCFIS WHERE DF_DOCFIS.ID = TITULOS.ID_DOCFIS)::TEXT ||'.'||(TITULOS.PARCELA)::TEXT)::TEXT
FROM FINANCAS.TITULOS 
WHERE TITULOS.NUMERO IS NULL

-- ATUALIZAR O NÚMERO DO TÍTULO DE ACORDO COM A NOTA
UPDATE FINANCAS.TITULOS
SET NUMERO = ((SELECT DISTINCT NUMERO FROM NS.DF_DOCFIS WHERE DF_DOCFIS.ID = TITULOS.ID_DOCFIS)::TEXT ||'.'||(TITULOS.PARCELA)::TEXT)::TEXT
WHERE NUMERO IS NULL



-- ATUALIZA A DATA DE EMISSÃO DA DOCFIS (PRE RPS) COM A DATA DE EMISSAO DO TITULO -- FATURA DE LOCAÇÃO
UPDATE NS.DF_DOCFIS N SET N.EMISSAO = (SELECT EMISSAO FROM FINANCAS.TITULOS T WHERE T.ID_DOCFIS = N.ID LIMIT 1) 
WHERE N.EMISSAO IS NULL 
AND N.CONTRATO IN (SELECT CONTRATO FROM FINANCAS.CONTRATOS WHERE TIPOCONTRATO = 1 AND PERFILCONTRATO = 'L')
AND N.ID IN (SELECT ID_DOCFIS FROM FINANCAS.TITULOS);






