-- BUSCAR CHAMADO DO ATENDIMENTO WEB
SELECT ATENDIMENTO, NUMEROPROTOCOLO, SINTOMA AS TEXTO
FROM SERVICOS.ATENDIMENTOS 
WHERE PARTICIPANTE = 'be304d23-0da4-4d81-a5c5-3ae3fd38fec4'
AND SINTOMA ILIKE '%layout%notas%'
UNION 
SELECT A.ATENDIMENTO, A.NUMEROPROTOCOLO, F.HISTORICO AS TEXTO
FROM SERVICOS.ATENDIMENTOS A
LEFT JOIN NS.FOLLOWUPS F ON A.ATENDIMENTO = F.ATENDIMENTO
WHERE A.PARTICIPANTE = 'be304d23-0da4-4d81-a5c5-3ae3fd38fec4'
AND F.HISTORICO ILIKE '%layout%notas%'
--ORDER BY A.NUMEROPROTOCOLO ASC