-- LISTAGEM DE CLIENTES ATIVOS POR VENDEDOR
SELECT DISTINCT P.PESSOA "CÓD. CLIENTE", P.NOME "RAZÃO SOCIAL CLIENTE", P.NOMEFANTASIA "NOME FANTASIA CLIENTE",
EN.UF "UF CLIENTE", V.PESSOA "CÓD. VENDEDOR", V.NOMEFANTASIA "NOME VENDEDOR"
FROM FINANCAS.ITENSCONTRATOS IC
INNER JOIN FINANCAS.CONTRATOS C ON C.CONTRATO = IC.CONTRATO
INNER JOIN NS.PESSOAS P ON P.ID = C.PARTICIPANTE
INNER JOIN CRM.SEGMENTOSATUACAO S ON P.SEGMENTOATUACAO = S.SEGMENTOATUACAO
INNER JOIN SERVICOS.SERVICOS SE ON SE.ID = IC.SERVICO
INNER JOIN NS.ENDERECOS EN ON EN.ID_PESSOA = P.ID AND EN.TIPOENDERECO = 0
LEFT JOIN NS.PESSOAS V ON V.ID = P.VENDEDOR
WHERE C.TIPOCONTRATO = 1
AND IC.CANCELADO = FALSE
AND IC.PROCESSADO = TRUE
AND IC.VALOR > 0
AND C.PERFILCONTRATO = 'S'::CHARACTER
AND IC.RECORRENTE = TRUE
AND IC.UNIDADENATUREZA = 2
AND IC.UNIDADEINTERVALONATUREZA = 2
ORDER BY V.PESSOA, P.PESSOA




-- CONTRATOS REAJUSTADOS NO PERIODO
SELECT DISTINCT P.PESSOA "CÓD. CLIENTE", P.NOME "RAZÃO SOCIAL CLIENTE", 
P.NOMEFANTASIA "NOME FANTASIA CLIENTE", C.CODIGO "CONTRATO"
FROM FINANCAS.ITENSCONTRATOS IC
INNER JOIN FINANCAS.CONTRATOS C ON C.CONTRATO = IC.CONTRATO
INNER JOIN NS.PESSOAS P ON P.ID = C.PARTICIPANTE
WHERE C.TIPOCONTRATO = 1
AND IC.CANCELADO = FALSE
AND IC.PROCESSADO = TRUE
AND IC.VALOR > 0
AND C.PERFILCONTRATO = 'S'::CHARACTER
AND IC.RECORRENTE = TRUE
AND IC.UNIDADENATUREZA = 2
AND IC.UNIDADEINTERVALONATUREZA = 2
AND IC.DATAPROXIMOREAJUSTE BETWEEN '2019-11-01' AND '2019-11-30'
AND IC.TIPOSUSPENSAO = 0
ORDER BY P.PESSOA, C.CODIGO