SELECT UF, UFLOCAL, INTERNO 
FROM SCRITTA.TABICMS
WHERE UFLOCAL = UF AND UF <> 'EX'	
ORDER BY UF



UPDATE SCRITTA.TABICMS SET INTERNO = 17 WHERE UFLOCAL = 'AC' AND UF = 'AC';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'AL' AND UF = 'AL';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'AM' AND UF = 'AM';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'AP' AND UF = 'AP';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'BA' AND UF = 'BA';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'CE' AND UF = 'CE';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'DF' AND UF = 'DF';
UPDATE SCRITTA.TABICMS SET INTERNO = 17 WHERE UFLOCAL = 'ES' AND UF = 'ES';
UPDATE SCRITTA.TABICMS SET INTERNO = 17 WHERE UFLOCAL = 'GO' AND UF = 'GO';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'MA' AND UF = 'MA';
UPDATE SCRITTA.TABICMS SET INTERNO = 17 WHERE UFLOCAL = 'MT' AND UF = 'MT';
UPDATE SCRITTA.TABICMS SET INTERNO = 17 WHERE UFLOCAL = 'MS' AND UF = 'MS';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'MG' AND UF = 'MG';
UPDATE SCRITTA.TABICMS SET INTERNO = 17 WHERE UFLOCAL = 'PA' AND UF = 'PA';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'PB' AND UF = 'PB';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'PR' AND UF = 'PR';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'PE' AND UF = 'PE';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'PI' AND UF = 'PI';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'RN' AND UF = 'RN';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'RS' AND UF = 'RS';
UPDATE SCRITTA.TABICMS SET INTERNO = 20 WHERE UFLOCAL = 'RJ' AND UF = 'RJ';
UPDATE SCRITTA.TABICMS SET INTERNO = 17.5 WHERE UFLOCAL = 'RO' AND UF = 'RO';
UPDATE SCRITTA.TABICMS SET INTERNO = 17 WHERE UFLOCAL = 'RR' AND UF = 'RR';
UPDATE SCRITTA.TABICMS SET INTERNO = 17 WHERE UFLOCAL = 'SC' AND UF = 'SC';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'SP' AND UF = 'SP';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'SE' AND UF = 'SE';
UPDATE SCRITTA.TABICMS SET INTERNO = 18 WHERE UFLOCAL = 'TO' AND UF = 'TO';


