
-- EXCLUIR RATEIOS FINANCEIROS DOS TÍTULOS
DELETE FROM FINANCAS.RATEIOSFINANCEIROS
WHERE DOCUMENTORATEADO IN (
SELECT DOCUMENTORATEADO FROM FINANCAS.TITULOS 
WHERE ID_ESTABELECIMENTO = 'df82a320-fd92-40c5-a015-ea6b9fcef9c4'
AND NUMERO ILIKE 'GNR%');

-- EXCLUIR RATEIOS FINANCEIROS DAS BAIXAS
DELETE FROM FINANCAS.RATEIOSFINANCEIROS
WHERE DOCUMENTORATEADO IN (
SELECT DOCUMENTORATEADO FROM FINANCAS.LANCAMENTOSCONTAS
WHERE LANCAMENTOCONTA IN (
SELECT LANCAMENTOCONTA FROM FINANCAS.BAIXAS
WHERE ID_TITULO IN (
SELECT ID FROM FINANCAS.TITULOS 
WHERE ID_ESTABELECIMENTO = 'df82a320-fd92-40c5-a015-ea6b9fcef9c4'
AND NUMERO ILIKE 'GNR%')));

-- EXCLUIR REGISTROS DE BAIXAS DE TÍTULOS
CREATE TABLE FINANCAS.LCTEMP AS SELECT LANCAMENTOCONTA FROM FINANCAS.LANCAMENTOSCONTAS
WHERE LANCAMENTOCONTA IN (
SELECT LANCAMENTOCONTA FROM FINANCAS.BAIXAS
WHERE ID_TITULO IN (
SELECT ID FROM FINANCAS.TITULOS 
WHERE ID_ESTABELECIMENTO = 'df82a320-fd92-40c5-a015-ea6b9fcef9c4'
AND NUMERO ILIKE 'GNR%'));

DELETE FROM FINANCAS.BAIXAS
WHERE ID_TITULO IN (
SELECT ID FROM FINANCAS.TITULOS 
WHERE ID_ESTABELECIMENTO = 'df82a320-fd92-40c5-a015-ea6b9fcef9c4'
AND NUMERO ILIKE 'GNR%');

DELETE FROM FINANCAS.LANCAMENTOSCONTAS
WHERE LANCAMENTOCONTA IN (SELECT LANCAMENTOCONTA FROM FINANCAS.LCTEMP);

DROP TABLE FINANCAS.LCTEMP;

-- EXCLUIR TÍTULOS DO ESTABELECIMENTO '212'
DELETE FROM FINANCAS.TITULOS 
WHERE ID_ESTABELECIMENTO = 'df82a320-fd92-40c5-a015-ea6b9fcef9c4'
AND NUMERO ILIKE 'GNR%';

-- ATUALIZAR O SALDO DA CONTA CORRENTE
SELECT FINANCAS.ATUALIZASADOCONTA('9a9a7ad8-e603-49bc-99bc-730eb04b5e07');

