-- EXCLUIR BAIXAS DE TÍTULOS
DO
$$
DECLARE R RECORD;
	BEGIN
	FOR R IN (SELECT * FROM FINANCAS.TITULOS WHERE ID_ESTABELECIMENTO = 'df82a320-fd92-40c5-a015-ea6b9fcef9c4' AND (NUMERO ILIKE 'GNRNY%' OR NUMERO ILIKE 'GNR NY%')) LOOP
	RAISE NOTICE 'EXCLUINDO BAIXA DO TÍTULO %', R.NUMERO;
	DELETE FROM FINANCAS.BAIXAS WHERE ID_TITULO = R.ID_TITULO
	END LOOP;
	END;
$$;


-- EXCLUIR BAIXA DE TÍTULOS
DO
$$
DECLARE R RECORD;
BEGIN
FOR R IN (
SELECT LC.LANCAMENTOCONTA, T.NUMERO, T.ID
FROM FINANCAS.LANCAMENTOSCONTAS LC
JOIN FINANCAS.BAIXAS B ON B.LANCAMENTOCONTA = LC.LANCAMENTOCONTA
JOIN FINANCAS.TITULOS T ON T.ID = B.ID_TITULO
WHERE T.ID_ESTABELECIMENTO = 'df82a320-fd92-40c5-a015-ea6b9fcef9c4'
AND T.NUMERO ILIKE 'GNR%') LOOP
RAISE NOTICE 'EXCLUINDO REGISTROS DE BAIXA DO TÍTULO %', R.NUMERO;
DELETE FROM FINANCAS.LANCAMENTOSCONTAS WHERE LANCAMENTOCONTA = R.LANCAMENTOCONTA;
DELETE FROM FINANCAS.BAIXAS WHERE ID_TITULO = R.ID;
END LOOP;
END;
$$;