WITH CLIENTES AS (
SELECT DISTINCT P.ID
FROM FINANCAS.ITENSCONTRATOS IC
INNER JOIN FINANCAS.CONTRATOS C ON C.CONTRATO = IC.CONTRATO
INNER JOIN NS.PESSOAS P ON P.ID = C.PARTICIPANTE
INNER JOIN SERVICOS.SERVICOS SE ON SE.ID = IC.SERVICO
WHERE SE.SERVICO IN ('MRM')
AND P.REPRESENTANTETECNICOATIVADO = 0
AND P.REPRESENTANTECOMERCIALATIVADO = 0
AND C.TIPOCONTRATO = 1
AND SE.GERACOBRANCA = 1
AND IC.PROCESSADO = TRUE
AND IC.RECORRENTE = TRUE
AND C.CANCELADO = FALSE
AND IC.CANCELADO = FALSE)
SELECT DISTINCT
P.PESSOA "CÓDIGO CLIENTE",
P.NOME "NOME CLIENTE",
P.EMAIL "E-MAIL CLIENTE",
P.DATACADASTRO "DATA DE CADASTRO DO CLIENTE",
S.DESCRICAO "SEGMENTO DE ATUAÇÃO",
V.PESSOA "VENDEDOR",
'MRM,'::TEXT ||REPLACE(REPLACE(ARRAY_AGG(DISTINCT(SE.SERVICO))::TEXT, '{', '')::TEXT, '}', '') "SISTEMAS",
REPLACE(REPLACE(ARRAY_AGG(DISTINCT('('||T.DDD||')'||T.TELEFONE))::TEXT, '{', '')::TEXT, '}', '') "TELEFONES"  
FROM NS.PESSOAS P
INNER JOIN CLIENTES A ON A.ID = P.ID
JOIN FINANCAS.CONTRATOS C ON C.PARTICIPANTE = P.ID
JOIN FINANCAS.ITENSCONTRATOS IC ON IC.CONTRATO = C.CONTRATO
JOIN SERVICOS.SERVICOS SE ON SE.ID = IC.SERVICO
JOIN CRM.SEGMENTOSATUACAO S ON P.SEGMENTOATUACAO = S.SEGMENTOATUACAO
JOIN NS.PESSOAS V ON V.ID = P.VENDEDOR
LEFT JOIN NS.TELEFONES T ON T.ID_PESSOA = P.ID
WHERE
SE.SERVICO IN --('MET', 'MCW', 'MZW', 'MST', 'MCW2', 'MET2', 'MCMN', 'MCMRNFCE', 'MCMR', 'MMW')
('MSQL-CONTABIL', 'MSQL-SCRITTA', 'MSQL-PERSONA', 'MSQL-INTEGRATTOCONT', 'MERP-FINANCAS', 'MERP-ESTOQUE', 
'MERP-CRM', 'MERP-COMPRAS', 'MERP-SERVICOS', 'MERP-PERSONA', 'MERP-SCRITTA', 'MERP-CONTABIL', 'MERP-ATENDIMENTO') 
AND P.REPRESENTANTETECNICOATIVADO = 0
AND P.REPRESENTANTECOMERCIALATIVADO = 0
AND C.TIPOCONTRATO = 1
AND SE.GERACOBRANCA = 1
AND IC.PROCESSADO = TRUE
AND IC.RECORRENTE = TRUE
AND C.CANCELADO = FALSE
AND IC.CANCELADO = FALSE
GROUP BY P.PESSOA, P.NOME, P.EMAIL, P.DATACADASTRO, S.DESCRICAO, V.PESSOA
ORDER BY P.NOME 