-- BUSCAR ATENDIMENTOS COM SOLICITAÇÃO DE BACKUPS
SELECT U.LOGIN, F.DATA, A.NUMEROPROTOCOLO, P.NOME, F.HISTORICO
FROM NS.FOLLOWUPS F
JOIN NS.USUARIOS U ON U.USUARIO = F.USUARIO
JOIN NS.PESSOAS P ON P.ID = F.PARTICIPANTE
JOIN SERVICOS.ATENDIMENTOS A ON A.ATENDIMENTO = F.ATENDIMENTO
WHERE F.DATA BETWEEN '2017-09-18' AND '2017-09-22'
AND U.LOGIN IN ('LUIZCOUTINHO', 'CARLOSNASCIMENTO', 'GUSTAVOCASTILHO', 'LUIZFISCHER', 
'SAULOMACEDO', 'TIAGOSILVEIRA', 'HENRIQUEWONG')
AND (F.HISTORICO ILIKE '%backup%' OR F.HISTORICO ILIKE '%bkp%')
ORDER BY U.LOGIN, F.DATA;



-- tipo smallint, -- 0:Resposta, 1:Comentário

-- BUSCAR COMENTARIOS INTERNOS POR TÉCNICO E PERÍODO
SELECT U.LOGIN, COUNT(F.HISTORICO)
FROM NS.FOLLOWUPS F
JOIN NS.USUARIOS U ON U.USUARIO = F.USUARIO
JOIN NS.PESSOAS P ON P.ID = F.PARTICIPANTE
JOIN SERVICOS.ATENDIMENTOS A ON A.ATENDIMENTO = F.ATENDIMENTO
WHERE F.DATA BETWEEN '2017-10-01' AND '2017-10-31'
AND U.LOGIN IN ('LUIZCOUTINHO', 'CARLOSNASCIMENTO', 'GUSTAVOCASTILHO', 'LUIZFISCHER', 
'SAULOMACEDO', 'TIAGOSILVEIRA', 'HENRIQUEWONG')
AND F.TIPO = 1
GROUP BY U.LOGIN
ORDER BY COUNT(F.HISTORICO) DESC;