-- EXIBIR DADOS DE PARCELAS DE CARTÃO
SELECT NUMERO, SUBSTRING(NUMERO FROM 1 FOR 12), PARCELA, TOTALPARCELAS, NUMEROPARCELACARTAO
FROM FINANCAS.TITULOS
WHERE NUMERO ILIKE '43887.%'
ORDER BY NUMERO

-- ATUALIZAR A PARCELA E O NÚMERO DO TÍTULO A PARTIR DA PARCELA DO CARTÃO (ATÉ 9X)
UPDATE FINANCAS.TITULOS 
SET PARCELA = NUMEROPARCELACARTAO, NUMERO = SUBSTRING(NUMERO FROM 1 FOR 12) || '0' || (NUMEROPARCELACARTAO)::TEXT
WHERE NUMERO ILIKE '43887.%'