DO
$Atualiza_lancamentos$
BEGIN

-- DESABILITANDO AS TRIGGERS DE CONTABILIZAÇÃO
ALTER TABLE FINANCAS.LANCAMENTOSCONTAS 
DISABLE TRIGGER financas_lancamentosconta_contabilizarlancamentoconta;

ALTER TABLE FINANCAS.LANCAMENTOSCONTAS 
DISABLE TRIGGER financas_lancamentosconta_contabilizar_lancamentoconta_update;

-- ATUALIZA OS LANÇAMENTOS DE JANEIRO A AGOSTO DE 2016 PARA CONCILIADO
UPDATE FINANCAS.LANCAMENTOSCONTAS
SET SITUACAO = 2
WHERE SITUACAO = 1 AND DATA BETWEEN '2016-01-01' AND '2016-08-31';

-- REABILITANDO AS TRIGGERS DE CONTABILIZAÇÃO
ALTER TABLE FINANCAS.LANCAMENTOSCONTAS 
ENABLE TRIGGER financas_lancamentosconta_contabilizarlancamentoconta;

ALTER TABLE FINANCAS.LANCAMENTOSCONTAS 
ENABLE TRIGGER financas_lancamentosconta_contabilizar_lancamentoconta_update;

END;
$Atualiza_lancamentos$;