/*
Autor: Marlon Souza
Data: 22/06/2016
Descrição: Add configuracao de contratos rec/pag financeiro e de locaçao nas configuracoes dnf
*/

DO
$MY_CARGA$
  DECLARE T_SEQ_RECEBER BIGINT;
  DECLARE T_SEQ_PAGAR BIGINT;
BEGIN

  -- PEGA PROXIMO VALOR DAS SEQUENCES
  SELECT NEXTVAL('financas.titulocobrancaseq') INTO T_SEQ_RECEBER;
  SELECT NEXTVAL('financas.titulocontratopagarseq') INTO T_SEQ_PAGAR;

  DROP TABLE IF EXISTS TMP_ENTIDADES;
  CREATE TEMPORARY TABLE TMP_ENTIDADES (ENTIDADE INTEGER);
  INSERT INTO TMP_ENTIDADES (ENTIDADE) VALUES (7),(8),(9),(10);

  INSERT INTO NS.CONFIGURACOESNUMERACOESDNF (GRUPOEMPRESARIAL, ENTIDADE, TIPONUMERACAO, MODOGERACAO)
  SELECT GRP.GRUPOEMPRESARIAL, TMP.ENTIDADE, 2::SMALLINT, 0::SMALLINT
    FROM NS.GRUPOSEMPRESARIAIS GRP, TMP_ENTIDADES TMP;

  INSERT INTO NS.ITENSCONFIGURACOESNUMERACOESDNF (CONFIGURACAONUMERACAODNF, CHAVEENTIDADE, PROXIMONUMERO)
  SELECT DNF.CONFIGURACAONUMERACAODNF, DNF.GRUPOEMPRESARIAL, CASE WHEN DNF.ENTIDADE IN (7,8) THEN T_SEQ_RECEBER ELSE T_SEQ_PAGAR END VALOR
    FROM NS.CONFIGURACOESNUMERACOESDNF DNF
    JOIN TMP_ENTIDADES TMP ON DNF.ENTIDADE = TMP.ENTIDADE;

  DROP TABLE IF EXISTS TMP_ENTIDADES;

END;
$MY_CARGA$;

/* SELECT * FROM NS.CONFIGURACOESNUMERACOESDNF WHERE ENTIDADE IN ('7', '8', '9', '10');
   DELETE FROM NS.CONFIGURACOESNUMERACOESDNF WHERE ENTIDADE IN ('7', '8', '9', '10');
*/