SELECT T.NUMERO, T.EMISSAO, T.VENCIMENTO, T.VALOR, P.PESSOA, P.NOME, 
C.CODIGO, FINANCAS.GET_SITUACAOTITULO(T.SITUACAO) AS SITUACAO
FROM FINANCAS.TITULOS T
JOIN NS.PESSOAS P ON P.ID = T.ID_PESSOA
JOIN FINANCAS.CONTAS C ON C.CONTA = T.CONTA
WHERE T.SITUACAO IN (0, 3, 6)
AND T.SINAL = 0
AND C.CODIGO IN ('ITAUN', 'ITAUNATIV', 'ITAUS')
AND T.VENCIMENTO BETWEEN '2017-01-01' AND '2018-06-30'
ORDER BY T.VENCIMENTO, NUMERO