-- CRIANDO BACKUP DAS TABELAS ENVOLVIDAS
CREATE TABLE NS.CONVUNIDADES_BKP AS SELECT * FROM NS.CONVUNIDADES;
CREATE TABLE ESTOQUE.PRODUTOSCONVUNIDADES_BKP AS SELECT * FROM ESTOQUE.PRODUTOSCONVUNIDADES;

-- CRIANDO AS CONVERSÕES PARA OS ITENS
DO 
$$ 
	DECLARE _ITEM RECORD;
BEGIN
	FOR _ITEM IN (SELECT ID, UNIDADE FROM ESTOQUE.ITENS ORDER BY ITEM)
	LOOP
		IF NOT EXISTS(SELECT 1 FROM NS.CONVUNIDADES WHERE ID_ITEM = _ITEM.ID AND UNIDADE = _ITEM.UNIDADE) THEN
			INSERT INTO NS.CONVUNIDADES(ID_ITEM, UNIDADE, UNIDADEPADRAO, RAZAO)
			VALUES(_ITEM.ID, _ITEM.UNIDADE, _ITEM.UNIDADE, 1);
		END IF;
	END LOOP;
END 
$$;

-- CRIANDO AS CONVERSÕES PARA OS PRODUTOS
DO 
$$ 
	DECLARE _PRODUTO RECORD;
BEGIN
	FOR _PRODUTO IN (SELECT PRODUTO AS ID, UNIDADEDEMEDIDA AS UNIDADE FROM ESTOQUE.PRODUTOS ORDER BY CODIGO)
	LOOP
		IF NOT EXISTS(SELECT 1 FROM ESTOQUE.PRODUTOSCONVUNIDADES WHERE PRODUTO = _PRODUTO.ID AND UNIDADE = _PRODUTO.UNIDADE) THEN
			INSERT INTO ESTOQUE.PRODUTOSCONVUNIDADES(PRODUTO, UNIDADE, UNIDADEPADRAO, RAZAO)
			VALUES(_PRODUTO.ID, _PRODUTO.UNIDADE, _PRODUTO.UNIDADE, 1);
		END IF;
	END LOOP;
END 
$$;