-- CONTADORES DO RIO DE JANEIRO
SELECT DISTINCT 
P.NOME "RAZÃO SOCIAL", P.EMAIL "E-MAIL",
COALESCE(EN.TIPOLOGRADOURO, 'R') ||' '|| COALESCE(EN.LOGRADOURO, ' ') ||', '|| COALESCE(EN.NUMERO, 'S/N') ||' '|| COALESCE(EN.COMPLEMENTO, ' ')  AS "ENDEREÇO",
EN.BAIRRO "BAIRRO", EN.CEP "CEP", EN.CIDADE "CIDADE", EN.UF "UF"
FROM FINANCAS.ITENSCONTRATOS IC
INNER JOIN FINANCAS.CONTRATOS C ON C.CONTRATO = IC.CONTRATO
INNER JOIN NS.PESSOAS P ON P.ID = C.PARTICIPANTE
INNER JOIN CRM.SEGMENTOSATUACAO S ON P.SEGMENTOATUACAO = S.SEGMENTOATUACAO
INNER JOIN SERVICOS.SERVICOS SE ON SE.ID = IC.SERVICO
INNER JOIN NS.ENDERECOS EN ON EN.ID_PESSOA = P.ID AND EN.TIPOENDERECO = 0
WHERE C.TIPOCONTRATO = 1
AND IC.CANCELADO = FALSE
AND IC.PROCESSADO = TRUE
AND IC.VALOR > 0
AND C.PERFILCONTRATO = 'S'::CHARACTER
AND IC.RECORRENTE = TRUE
AND IC.UNIDADENATUREZA = 2
AND IC.UNIDADEINTERVALONATUREZA = 2
AND SE.SERVICO IN ( 'MET', 'MET2', 'MGW', 'MCT', 'MBASIC', 'MCC', 'MCM', 'MPLUS', 'MST', 'MPREMIUM', 
'MSQL-CONTABIL', 'MSQL-INTEGRATTOCONT', 'MSQL-INTEGRATTOFIN')
AND EN.UF = 'RJ'
AND S.CODIGO IN ('AUD', 'CON', 'CTB')
ORDER BY P.NOME