-- BUSCAR NFSE E RPS ATIVOS NO PERÍODO
SELECT 	E.CODIGO AS ESTABELECIMENTO, 
	D.NUMERO AS NOTA, 
	D.RPS AS RPS, 
	D.EMISSAO, 
	D.LANCAMENTO,
	REPLACE((C.PESSOA|| ' - ' ||C.NOME)::TEXT, ',', '') AS CLIENTE, 
	REPLACE(D.VALOR::TEXT, '.', ',') AS VALOR
FROM NS.DF_DOCFIS D
JOIN NS.ESTABELECIMENTOS E ON E.ESTABELECIMENTO = D.ID_ESTABELECIMENTO
JOIN NS.PESSOAS C ON C.ID = D.ID_PESSOA
WHERE STATUSRPS NOT IN (7, 1, 2)
	AND D.MODELO IN ('RPS', 'NES')
	AND SITUACAO <> 15
	AND (D.EMISSAO BETWEEN '2016-09-01' AND '2016-09-30')
ORDER BY E.CODIGO, D.EMISSAO, D.NUMERO