-- BUSCAR CONTA PADRÃO DUPLICADA NO FORNECEDOR / TOMADOR DE FOLHA
SELECT PESSOA, NOME FROM NS.PESSOAS WHERE ID IN(
SELECT ID_FORNECEDOR
FROM FINANCAS.CONTASFORNECEDORES
WHERE PADRAO = TRUE AND EXCLUIDA = FALSE
GROUP BY ID_FORNECEDOR
HAVING COUNT(ID_FORNECEDOR) > 1);