
-- CASE COM SITUAÇÕES DE TÍTULOS A RECEBER

SELECT NUMERO, EMISSAO, VENCIMENTO, VALOR, 
CASE
WHEN SITUACAO = 0 THEN 'Aberto'
WHEN SITUACAO = 1 THEN 'Quitado'
WHEN SITUACAO = 2 THEN 'Em Débito'
WHEN SITUACAO = 3 THEN 'Cancelado'
WHEN SITUACAO = 4 THEN 'Protestado'
WHEN SITUACAO = 5 THEN 'Estornado'
WHEN SITUACAO = 6 THEN 'Agendado'
WHEN SITUACAO = 7 THEN 'Suspenso'
WHEN SITUACAO = 8 THEN 'Aberto Descontado'
ELSE NULL::text
END AS SITUACAO_TITULO
FROM FINANCAS.TITULOS
WHERE SINAL = 0
ORDER BY VENCIMENTO DESC