--RELATÓRIO DE TÍTULOS SUSPENSOS COM DATA DE SUSPENSÃO
SELECT T.NUMERO "TíTULO",
      T.EMISSAO "EMISSãO",
      P.PESSOA "CLIENTE",
      P.NOME "RAZAO SOCIAL",
      T.ORIGEMTEXTO "ORIGEM",
      COALESCE(T.VALOR, T.VALORBRUTO,'0') "VALOR",
      T.VENCIMENTO "VENCIMENTO", 
      CASE WHEN T.SITUACAO = 7 THEN 'SUSPENSO'
      WHEN T.SITUACAO = 0 THEN 'ABERTO'
      WHEN T.SITUACAO = 1 THEN 'QUITADO'
      WHEN T.SITUACAO = 3 THEN 'CANCELADO'
      END "SITUAçãO", 
      T.NOSSONUMERO "NOSSONUMERO", 
      DF.NUMERO "NFSE", 
      DF.RPS "RPS", 
      E.CODIGO "ESTABELECIMENTO", 
      AC.DATAPRINCIPAL "DATA SUSPENSãO",
      CASE WHEN B.SITUACAO = 2 THEN 'RETIRADO DA COBRANçA'
           WHEN B.SITUACAO = 3 THEN 'ENTRADA CONFIRMADA'
           WHEN B.SITUACAO = 8 THEN 'ENVIADO'
      END "SITUAçãO BOLETO"
FROM FINANCAS.TITULOS T
JOIN NS.PESSOAS P ON P.ID = T.ID_PESSOA
JOIN NS.DF_DOCFIS DF ON DF.ID = T.ID_DOCFIS
JOIN NS.ESTABELECIMENTOS E ON E.ESTABELECIMENTO = T.ID_ESTABELECIMENTO
JOIN NS.DF_SERVICOS DS ON DS.TITULO = T.ID
JOIN FINANCAS.ITENSCONTRATOS IC ON IC.ITEMCONTRATO = DS.ITEMCONTRATO
JOIN FINANCAS.ALTERACOESCONTRATOS AC ON AC.ITEMCONTRATO = IC.ITEMCONTRATO
LEFT JOIN FINANCAS.BOLETOSBANCARIOS B ON B.ID_TITULO = T.ID
WHERE T.SITUACAO = 7
AND AC.TIPO IN (3, 4)
GROUP BY T.NUMERO, T.EMISSAO, P.PESSOA, P.NOME, T.ORIGEMTEXTO, T.VALOR, T.VALORBRUTO, 
T.VENCIMENTO, T.SITUACAO, T.NOSSONUMERO, DF.NUMERO, DF.RPS, E.CODIGO, AC.DATAPRINCIPAL, 
B.BOLETOBANCARIO, B.SITUACAO