UPDATE FINANCAS.TITULOS SET DATAPROVISORIA = FALSE, VALORPROVISORIO = FALSE 
WHERE ID IN (
SELECT T.ID --, T.NUMERO, T.EMISSAO, T.VENCIMENTO, P.PESSOA, P.NOME, T.VALOR, T.DATAPROVISORIA, T.VALORPROVISORIO, E.CODIGO AS ESTABELECIMENTO, 
--C.CODIGO AS CONTA, T.ORIGEMTEXTO, T.LAYOUTCOBRANCA
FROM FINANCAS.TITULOS T
JOIN NS.PESSOAS P ON (P.ID = T.ID_PESSOA)
JOIN NS.ESTABELECIMENTOS E ON (E.ESTABELECIMENTO = T.ID_ESTABELECIMENTO)
JOIN FINANCAS.CONTAS C ON (C.CONTA = T.CONTA)
WHERE SINAL = 0
AND T.ORIGEMTEXTO = 'Contrato'
AND T.SITUACAOTEXTO = 'Aberto' 
AND E.CODIGO = 'NASAJON'
AND T.VENCIMENTO BETWEEN '2016-10-01' AND '2016-10-31'
AND C.CODIGO = 'ITAUN'
AND T.NOSSONUMERO IS NULL
AND (T.DATAPROVISORIA OR T.VALORPROVISORIO)
);
--ORDER BY T.NUMERO
