------------------------------------------------ JOGA TODOS OS TITULOS DO LANCAMENTO 449816 PARA O LANCAMENTO 449837
UPDATE ERP.BAIXASRECEBER BR
   SET LANCAMENTOCONTA = 449837
 WHERE BR.LANCAMENTOCONTA = 449816;


------------------------------------------------ RODAR O ROBO QUE CRIA OS RATEIOS DOS TITULOS SEM RATEIOS [EMAIL]
CREATE OR REPLACE FUNCTION ERP.PREENCHERATEIOS() RETURNS VOID AS
$BODY$  
	DECLARE VDOCUMENTORATEADO_ID BIGINT;
	DECLARE REG_ITENSFATURAMENTOS RECORD;
	
BEGIN 

	FOR REG_ITENSFATURAMENTOS IN ( 	
	
	-- RECUPERA OS TITULOS QUE NAO POSSUEM DOCUMENTOS RATEADOS
	SELECT T.TITULORECEBER, T.VALOR, V.CENTROCUSTO, 2 /* CESSAO DE USO */ AS CLASSIFICACAOFINANCEIRA
	  FROM ERP.RPSS R
	  JOIN ERP.TITULOSRECEBER T ON ( R.RPS= T.RPS )						-- TITULOS RECEBER
	  JOIN ERP.PARTICIPANTES C  ON (C.PARTICIPANTE = R.PARTICIPANTE) 			-- CLIENTES
	  JOIN ERP.PARTICIPANTES V  ON ( C.VENDEDOR = V.PARTICIPANTE )				-- VENDEDORES
	  LEFT JOIN ERP.DOCUMENTOSRATEADOS DR ON ( DR.DOCUMENTORATEADO = T.DOCUMENTORATEADO )	-- DOCUMENTOSRATEADOS
	  LEFT JOIN ERP.RATEIOSFINANCEIROS RF ON ( RF.DOCUMENTORATEADO = DR.DOCUMENTORATEADO )	-- RATEIOSFINANCEIROS
	 WHERE R.EMISSAO >= '20140101'
	   AND ( T.DOCUMENTORATEADO IS NULL OR RF.CLASSIFICACAOFINANCEIRA IS NULL )
	 
	) LOOP

	-- CRIA DOCUMENTOSRATEADOS E RETORNA ID
	INSERT INTO ERP.DOCUMENTOSRATEADOS (DOCUMENTORATEADO, VALOR)
	VALUES (DEFAULT, REG_ITENSFATURAMENTOS.VALOR)
	RETURNING DOCUMENTORATEADO INTO VDOCUMENTORATEADO_ID;

	-- CRIA RATEIOSFINANCEIROS
	INSERT INTO ERP.RATEIOSFINANCEIROS (RATEIOFINANCEIRO, CENTROCUSTO, VALOR, CLASSIFICACAOFINANCEIRA, DOCUMENTORATEADO)
	VALUES (DEFAULT, REG_ITENSFATURAMENTOS.CENTROCUSTO, REG_ITENSFATURAMENTOS.VALOR, REG_ITENSFATURAMENTOS.CLASSIFICACAOFINANCEIRA, VDOCUMENTORATEADO_ID);
	 
	-- ATUALIZA TITULOS
	UPDATE ERP.TITULOSRECEBER 
	   SET DOCUMENTORATEADO = VDOCUMENTORATEADO_ID
	 WHERE TITULORECEBER = REG_ITENSFATURAMENTOS.TITULORECEBER;
	 
        END LOOP;	 

   
END;
$BODY$
LANGUAGE PLPGSQL VOLATILE
COST 100;

SELECT ERP.PREENCHERATEIOS();

DROP FUNCTION ERP.PREENCHERATEIOS();


------------------------------------------------ RODAR O ROBO QUE ATUALIZA OS RATEIOS DO LANCAMENTO COM BASE NOS RATEIOS DOS TITULOS DELE [ROBO DO LANCAMENTO]
DROP FUNCTION IF EXISTS ERP.ATUALIZACAO_CONTA_ERP();

CREATE OR REPLACE FUNCTION ERP.ATUALIZACAO_CONTA_ERP( IDLANCAMENTO BIGINT)
  RETURNS VOID AS
$BODY$ 
  DECLARE VALOR_LANCAMENTO NUMERIC(20,2);
  DECLARE ID_DOCRATEADO_AUX BIGINT;
  DECLARE ID_DOCRATEADO BIGINT;
  DECLARE REC RECORD;
     
BEGIN

	VALOR_LANCAMENTO = 0;

	SELECT DOCUMENTORATEADO 
	  FROM ERP.LANCAMENTOSCONTAS 
	 WHERE LANCAMENTOCONTA = IDLANCAMENTO 
	  INTO ID_DOCRATEADO_AUX;
	
	UPDATE ERP.LANCAMENTOSCONTAS 
	   SET DOCUMENTORATEADO = NULL 
	 WHERE LANCAMENTOCONTA = IDLANCAMENTO;

	DELETE 
	  FROM ERP.RATEIOSFINANCEIROS 
	 WHERE DOCUMENTORATEADO = ID_DOCRATEADO_AUX;
	
	DELETE 
	  FROM ERP.DOCUMENTOSRATEADOS 
	 WHERE DOCUMENTORATEADO = ID_DOCRATEADO_AUX;

	DROP TABLE IF EXISTS ERP.RATEIO_TEMP;
	CREATE TABLE ERP.RATEIO_TEMP ( CENTROCUSTO BIGINT, VALOR NUMERIC(20,2), CLASSIFICACAOFINANCEIRA BIGINT, DOCUMENTORATEADO BIGINT, VALORTITULO NUMERIC(20,2), VALORBAIXA NUMERIC(20,2));

	FOR REC IN 	
		SELECT T.*, BR.VALOR VALORBAIXA
		FROM ERP.TITULOSRECEBER T
		JOIN ERP.BAIXASRECEBER BR ON (T.TITULORECEBER = BR.TITULORECEBER)
		JOIN ERP.LANCAMENTOSCONTAS LC ON (LC.LANCAMENTOCONTA = BR.LANCAMENTOCONTA)
		WHERE LC.LANCAMENTOCONTA = IDLANCAMENTO
	LOOP
		-- RECUPERA O VALOR DO LANCAMENTO
		VALOR_LANCAMENTO = VALOR_LANCAMENTO + REC.VALORBAIXA;

		-- INSERT INTO RATEIO TEMPORARIO
		INSERT INTO ERP.RATEIO_TEMP ( CENTROCUSTO, VALOR, CLASSIFICACAOFINANCEIRA, VALORTITULO, VALORBAIXA )
			SELECT CENTROCUSTO, VALOR, CLASSIFICACAOFINANCEIRA, REC.VALOR, REC.VALORBAIXA
			  FROM ERP.RATEIOSFINANCEIROS 
			 WHERE DOCUMENTORATEADO = REC.DOCUMENTORATEADO;

	END LOOP;

	-- INSERT INTO DOCUMENTORATEADO
	INSERT INTO ERP.DOCUMENTOSRATEADOS(VALOR)
	VALUES (VALOR_LANCAMENTO)
	RETURNING DOCUMENTORATEADO INTO ID_DOCRATEADO;

	UPDATE ERP.RATEIO_TEMP
	   SET DOCUMENTORATEADO = ID_DOCRATEADO;

	INSERT INTO ERP.RATEIOSFINANCEIROS( CENTROCUSTO, VALOR, CLASSIFICACAOFINANCEIRA, DOCUMENTORATEADO)
	SELECT CENTROCUSTO, SUM(ROUND(((((VALOR * 100) / VALORTITULO) * VALORBAIXA) / 100 ),2)), CLASSIFICACAOFINANCEIRA, DOCUMENTORATEADO
	  FROM ERP.RATEIO_TEMP 
	 GROUP BY 1,3,4;

	UPDATE ERP.LANCAMENTOSCONTAS
	   SET VALOR = VALOR_LANCAMENTO,
	       DOCUMENTORATEADO = ID_DOCRATEADO
	 WHERE LANCAMENTOCONTA = IDLANCAMENTO;

	  DROP TABLE IF EXISTS ERP.RATEIO_TEMP;

END;
$BODY$
  LANGUAGE PLPGSQL VOLATILE
  COST 100;

SELECT ERP.ATUALIZACAO_CONTA_ERP(449837);
SELECT ERP.ATUALIZACAO_CONTA_ERP(449816);

DROP FUNCTION IF EXISTS ERP.ATUALIZACAO_CONTA_ERP();
