SELECT DISTINCT C.CODIGO, C.DESCRICAO, P.PESSOA, P.NOME, IC.DATAPROXIMOREAJUSTE, IC.INDICE
FROM FINANCAS.ITENSCONTRATOS IC
JOIN FINANCAS.CONTRATOS C ON (C.CONTRATO = IC.CONTRATO)
JOIN NS.PESSOAS P ON (P.ID = C.PARTICIPANTE)
JOIN NS.DF_DOCFIS DF ON (C.CONTRATO = DF.CONTRATO)
JOIN FINANCAS.PROCESSAMENTOSCONTRATOS PC ON (PC.PROCESSAMENTOCONTRATO = DF.PROCESSAMENTOCONTRATO)
WHERE IC.DATAPROXIMOREAJUSTE BETWEEN '2017-10-01' AND '2017-10-31'
--WHERE IC.RECORRENTE
AND IC.RECORRENTE 
AND IC.CANCELADO = FALSE
AND IC.PROCESSADO
AND (PC.MES = '9' OR PC.PROCESSAMENTOCONTRATO = 'c3be89ca-16fd-4a9a-b6f5-987a5484b671')
ORDER BY P.PESSOA

