-- QUANTIDADE DE CHAMADOS POR TIPO
SELECT 
       CASE
       		WHEN A.SINTOMA ILIKE '%5432%' THEN 'PORTA 5432'
		WHEN (A.SINTOMA ILIKE '%ATUALIZACAO%' OR A.SINTOMA ILIKE '%ATUALIZAÇÃO%') THEN 'ATUALIZAÇÃO'
		WHEN (A.SINTOMA ILIKE '%INSTALACAO%' OR A.SINTOMA ILIKE '%INSTALAÇÃO%') THEN 'INSTALAÇÃO'
		WHEN (A.SINTOMA ILIKE '%BACKUP%' OR A.SINTOMA ILIKE '%BKP%') THEN 'BACKUP'
		ELSE 'OUTROS' END "TIPO_CHAMADO",
       	SUM(1) "QTD_CHAMADOS"
FROM SERVICOS.ATENDIMENTOS A
JOIN NS.PESSOAS P ON P.ID = A.PARTICIPANTE
WHERE A.DATACRIACAO >= '2020-01-01' AND A.PARTICIPANTE IS NOT NULL AND P.REPRESENTANTE_TECNICO IS NULL
AND (A.SINTOMA ILIKE '%5432%' OR A.SINTOMA ILIKE '%ATUALIZACAO%' OR A.SINTOMA ILIKE '%ATUALIZAÇÃO%' OR A.SINTOMA ILIKE '%INSTALACAO%' OR
A.SINTOMA ILIKE '%INSTALAÇÃO%' OR A.SINTOMA ILIKE '%BACKUP%' OR A.SINTOMA ILIKE '%BKP%')
GROUP BY 1
ORDER BY 1


-- FILTRAR CHAMADOS POR TIPOS ESPECÍFICOS
SELECT A.DATACRIACAO, A.NUMEROPROTOCOLO, A.SINTOMA, A.CANAL, A.* 
FROM SERVICOS.ATENDIMENTOS A
JOIN NS.PESSOAS P ON P.ID = A.PARTICIPANTE
WHERE A.DATACRIACAO >= '2020-01-01' AND A.PARTICIPANTE IS NOT NULL AND P.REPRESENTANTE_TECNICO IS NULL
AND (A.SINTOMA ILIKE '%5432%' OR A.SINTOMA ILIKE '%ATUALIZACAO%' OR A.SINTOMA ILIKE '%ATUALIZAÇÃO%' OR A.SINTOMA ILIKE '%INSTALACAO%' OR
A.SINTOMA ILIKE '%INSTALAÇÃO%' OR A.SINTOMA ILIKE '%BACKUP%' OR A.SINTOMA ILIKE '%BKP%');


