CREATE TEMP TABLE CFESPELHO AS
SELECT
	C.CODIGO,
	CP.CODIGO CODIGOPAI,
	C.DESCRICAO,
	C.CODIGOCONTABIL,
	C.RESUMO,
	C.SITUACAO,
	C.NATUREZA,
	C.GRUPOEMPRESARIAL,
	C.RESUMOEXPLICATIVO,
	C.INICIOGRUPO,
	C.APENASAGRUPADOR
FROM
	NS.GRUPOSEMPRESARIAIS G
INNER JOIN
	FINANCAS.CLASSIFICACOESFINANCEIRAS C
ON
	G.GRUPOEMPRESARIAL = C.GRUPOEMPRESARIAL
LEFT JOIN
	FINANCAS.CLASSIFICACOESFINANCEIRAS CP
ON
	C.PAIID = CP.CLASSIFICACAOFINANCEIRA
WHERE
	G.CODIGO = 'INSERIR_CODIGO_DO_GRUPO';

INSERT INTO FINANCAS.CLASSIFICACOESFINANCEIRAS (CODIGO,DESCRICAO,CODIGOCONTABIL,RESUMO,SITUACAO,NATUREZA,GRUPOEMPRESARIAL,RESUMOEXPLICATIVO,INICIOGRUPO,APENASAGRUPADOR)
SELECT
	CFESPELHO.CODIGO,
	CFESPELHO.DESCRICAO,
	CFESPELHO.CODIGOCONTABIL,
	CFESPELHO.RESUMO,
	CFESPELHO.SITUACAO,
	CFESPELHO.NATUREZA,
	GRUPOSEMPRESARIAIS.GRUPOEMPRESARIAL,
	CFESPELHO.RESUMOEXPLICATIVO,
	CFESPELHO.INICIOGRUPO,
	CFESPELHO.APENASAGRUPADOR
FROM
	NS.GRUPOSEMPRESARIAIS,
	CFESPELHO
WHERE
	GRUPOSEMPRESARIAIS.CODIGO IN ('INSERIR_CODIGO_DO_GRUPO_QUE_RECEBERÁ_A_CLASSIFICACAO');

UPDATE FINANCAS.CLASSIFICACOESFINANCEIRAS
SET PAIID = CP.CLASSIFICACAOFINANCEIRA
FROM CFESPELHO, FINANCAS.CLASSIFICACOESFINANCEIRAS CP
WHERE CLASSIFICACOESFINANCEIRAS.CODIGO = CFESPELHO.CODIGO
AND CFESPELHO.CODIGOPAI = CP.CODIGO
AND CLASSIFICACOESFINANCEIRAS.GRUPOEMPRESARIAL = CP.GRUPOEMPRESARIAL;

DROP TABLE CFESPELHO;