SELECT ID, NUMERO, CONTA, SINAL FROM FINANCAS.TITULOS 
WHERE CONTA IS NULL OR CONTA = NULL;

SELECT COUNT(ID), SINAL FROM FINANCAS.TITULOS 
WHERE CONTA IS NULL OR CONTA = NULL
GROUP BY SINAL;

UPDATE FINANCAS.TITULOS 
SET CONTA = 'INFORMAR O ID DA CONTA'
WHERE CONTA IS NULL OR CONTA = NULL;