SELECT 
C.CODIGO,
DFS.DATAREAJUSTEITEMCONTRATO, 
DFS.DESCRICAO,
DFS.INICIOREFERENCIA "INI_REF_ATUAL",
DFS.FIMREFERENCIA "FIM_REF_ATUAL",
DFS.VALOR "VALOR_ATUAL",
ANT.INICIOREFERENCIA "INI_REF_ANTERIOR",
ANT.FIMREFERENCIA "FIM_REF_ANTERIOR", 
ANT.VALOR "VALOR_ANTERIOR"
FROM NS.DF_SERVICOS DFS 
LEFT JOIN NS.DF_SERVICOS ANT ON
(ANT.ITEMCONTRATO = DFS.ITEMCONTRATO AND ANT.FIMREFERENCIA = (DFS.INICIOREFERENCIA::DATE - 1)::DATE)
JOIN FINANCAS.CONTRATOS C ON C.CONTRATO = DFS.CONTRATO
JOIN FINANCAS.ITENSCONTRATOS IC ON IC.ITEMCONTRATO = DFS.ITEMCONTRATO
WHERE DFS.DATAREAJUSTEITEMCONTRATO BETWEEN '2019-11-01' AND '2019-11-30'
AND C.TIPOCONTRATO = 1
AND IC.CANCELADO = FALSE
AND IC.PROCESSADO = TRUE
AND IC.VALOR > 0
AND C.PERFILCONTRATO = 'S'::CHARACTER
AND IC.RECORRENTE = TRUE
AND IC.UNIDADENATUREZA = 2
AND IC.UNIDADEINTERVALONATUREZA = 2
AND IC.TIPOSUSPENSAO = 0